"""initial_schema

Revision ID: 662f533a736f
Revises: 
Create Date: 2026-09-08 08:42:26.134948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662f533a736f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ia_financial_analysis')
    op.drop_index(op.f('ix_credit_notes_id_invoice'), table_name='credit_notes')
    op.drop_column('credit_notes', 'id_invoice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_notes', sa.Column('id_invoice', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_credit_notes_id_invoice'), 'credit_notes', ['id_invoice'], unique=False)
    op.create_table('ia_financial_analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('razonamiento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_facturas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_devoluciones', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ingreso_neto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ia_financial_analysis_pkey'))
    )
    # ### end Alembic commands ###
